# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 322e51c3eb3137b15b1b603b20fc3e1a235ba3ab663364382839287071e75c81d73460140c419edd706c510d1390acb0156293460fdf800f7f0ca6567324d7a7

test:
  secret_key_base: dd6e730fa5cf0dae6f5a3a0274be28e764cb0f339dbf7e7449243773af543728c6fd05bb3c7671a19c79fb2c0a8e61a3b1fa4c4d71ad3b4894f24bb98b41e73d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
